### ISSUE TITLE
Adding Parameters

### ISSUE THREAD

**Issue by cefels** [tanrax/guetzli-recursively#1]
Hola Andros! Great script! It is exactly what I was l looking for. Just one question, how can I add the --quality parameter? I tried adding it in this line#24 like this but it didn't work:

call(['guetzli --quality 84', url, url_out])

**Comment by tanrax** [comment]
Hi and thanks! Why do you want to specify the quality? It is already set automatically. :)

**Comment by cefels** [comment]
Thanks for your quick reply! I've been testing and I see a big difference in the size using the default settings and the --quality 85 parameter (the quality looks the same for me):

-rw-r--r--   193540  original.jpg
-rw-r--r--   157841  guetzli-recursively.jpg
-rw-r--r--   157841  guetzli.jpg
-rw-r--r--   104091  guetzli85.jpg

**Comment by tanrax** [comment]
In that case I will implement this functionality !

**Comment by cefels** [comment]
Thanks! I read a little bit more about the call function and make it works like this:

call(['guetzli', "--quality", "85", url, url_out])

Saludos!

**Comment by cr8or1** [comment]
Hi,

Did you implement the functionality or not yet? How can i write the code so i can use the --quality 85?

**Comment by tanrax** [comment]
I just uploaded a new version. It will be soon, you can update it as follows.
```
pip install guetzli-recursively --upgrade
```
If next time you're in such a hurry to update, don't forget the pull requests :)
