### ISSUE TITLE
Error in line 7

### ISSUE THREAD

**Issue by Manuel5cc** [tanrax/guetzli-recursively#2]
When I run it I get this:
`File "guetzli-recursively.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
`

**Comment by tanrax** [comment]
Could you tell me which command you use and the Python version?

**Comment by Manuel5cc** [comment]
I have python 3.5.2 and used the command  `python3 guetzli-recursively.py /var/www/html/wp-content/uploads/2016/`

**Comment by tanrax** [comment]
I have uploaded an update. Try now.

**Comment by Manuel5cc** [comment]
Now it is working
